### PR TITLE
Updates and fixes the app diagnose command

### LINKED ISSUE #212: Review and fix the diagnose command
Check that it covers everything that is used in the current built-in templates.

### PR DESCRIPTION
**Pull request by vigoo**
Resolves #212

### CODE REVIEW

File: golem-cli/src/diagnose.rs [hunk 1]
```diff
@@ -170,57 +171,50 @@ impl SelectedLanguage {
...
             ],
+            Language::Go => vec![Tool::Go, Tool::TinyGo, Tool::WasmTools, Tool::GolemSdkGo],
             Language::JsTs => vec![
                 Tool::Npm,
                 Tool::Jco,
                 Tool::ComponentizeJs,
                 Tool::GolemSdkTypeScript,
             ],
-            Language::Python => vec![Tool::ComponentizePy],
+            Language::Python => vec![Tool::ComponentizePy, Tool::Uv],
```
Comment (noise64) [inline golem-cli/src/diagnose.rs:187]: i _think_ uv should manage comp-py too, so it should not be available globally

Comment (noise64) [reply golem-cli/src/diagnose.rs:187]: so we probably should test through uv

Comment (mschuwalow) [reply golem-cli/src/diagnose.rs:187]: yes, exactly :+1:

Comment (vigoo) [reply golem-cli/src/diagnose.rs:187]: what does "test through uv" mean?

Comment (noise64) [reply golem-cli/src/diagnose.rs:187]: `uv run componentize-py --version`
and that only works _in the component_ directory, not in the project root

Comment (noise64) [reply golem-cli/src/diagnose.rs:187]: and this also means that the dep order should be Uv, CompPy

**Review by noise64 — APPROVED** [review]

**Review by mschuwalow — APPROVED** [review]
